# Generated by Django 4.2.17 on 2025-06-14 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of balance change', max_digits=15, verbose_name='Amount')),
                ('operation_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('correction', 'Correction')], default='deposit', help_text='Type of balance operation', max_length=10, verbose_name='Operation type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional operation context data', verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Balance Log',
                'verbose_name_plural': 'Balance Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('inn', models.CharField(help_text='Taxpayer Identification Number (10 or 12 digits)', max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='INN must contain only digits', regex='^[0-9]*$')], verbose_name='INN')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current organization balance in currency units', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['inn'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(editable=False, help_text='Unique identifier of the payment operation', unique=True, verbose_name='Operation ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in currency units', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('payer_inn', models.CharField(help_text='Taxpayer Identification Number of the payer', max_length=12, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Payer INN')),
                ('document_number', models.CharField(help_text='Payment document reference number', max_length=50, verbose_name='Document number')),
                ('document_date', models.DateTimeField(help_text='Date and time when payment document was issued', verbose_name='Document date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-document_date'],
                'indexes': [models.Index(fields=['operation_id'], name='api_payment_operati_f52926_idx'), models.Index(fields=['payer_inn'], name='api_payment_payer_i_05435e_idx'), models.Index(fields=['document_date'], name='api_payment_documen_c51bd8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('operation_id',), name='unique_operation_id'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['inn'], name='api_organiz_inn_ebc9f5_idx'),
        ),
        migrations.AddField(
            model_name='balancelog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_logs', to='api.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='balancelog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_logs', to='api.payment', verbose_name='Payment'),
        ),
        migrations.AddIndex(
            model_name='balancelog',
            index=models.Index(fields=['organization'], name='api_balance_organiz_8ab769_idx'),
        ),
        migrations.AddIndex(
            model_name='balancelog',
            index=models.Index(fields=['created_at'], name='api_balance_created_4493bb_idx'),
        ),
        migrations.AddIndex(
            model_name='balancelog',
            index=models.Index(fields=['operation_type'], name='api_balance_operati_22a73a_idx'),
        ),
    ]
